# create a github action that builds an spring boot app, then build and push the image to github packages registry using docker commands

name: Build and push to GitHub Packages Registry

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: demo23010

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Build the app
      - name: Build with Maven
        run: mvn package -DskipTests

      # Log in to the Container registry
      - name: Log in to GitHub Packages Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push the image
      - name: Build and push
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest